language: node_js
node_js:
  - '18'
after_success: npm run coverage
notifications:
  email:
    recipients:
      - kjellmorten@integreat.io
    on_success: never # default: change
    on_failure: always # default: always
